### ISSUE TITLE
syntax issue in testthat tests

### ISSUE THREAD

**Issue by yrosseel** [sfcheung/semhelpinghands#77]
When testing lavaan 0.6-18 with the new syntax parser activated, I found some syntax mistakes in the tests. For example:

https://github.com/sfcheung/semhelpinghands/blob/10e288fd7007e8d18bc6be280fe97f1880bfa638/tests/testthat/test-ptable_to_syntax.R#L14

The problem is the space between ':' and '=', implying that 'ab:' is the left hand side, and '=' is the operator. Same issue on line 92. (The old parser removed all spaces, so this went by undetected). I may have missed others (as the tests stop as soon as an error is detected).

In the github version of lavaan, parser = "new" is the default.

**Comment by sfcheung** [comment]
Thanks for letting me know about this mistake. I will fix them soon.

(Coincidentally, I openned an issue on the `parser` argument  just now: https://github.com/yrosseel/lavaan/issues/335).

**Comment by sfcheung** [comment]
Fixed in the latest GitHub version (https://github.com/sfcheung/semhelpinghands/pull/78/commits/e6771401750a95fd62990b8a1850757b8cc4fda5).

I will submit this version to CRAN a few days later, just in case other problems related to the coming version of `lavaan` are found.

**Comment by sfcheung** [comment]
The latest version with the lavaan model syntax errors fixed is now on CRAN.
